# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacob Varner's Hoops Blog
email: jacob.varner14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  College basketball thoughts and analysis from Jacob Varner with a focus mostly on Auburn and the SEC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hoops.jacobvarner.com" # the base hostname & protocol for your site
twitter_username: jacobvarner14
timezone: America/Chicago

# Build settings
markdown: kramdown
