# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jacob Varner's Hoops Blog"
description: >
  Individual coverage of college basketball, with a focus on the SEC
url: http://hoops.jacobvarner.com # the base hostname & protocol for your site
author: jacobvarner14
twitter:
  username: jacobvarner14
timezone: America/Chicago
logo: /assets/images/logo.png

gems:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

collections:
  my_tags:
    output: true
    permalink: /tag/:name/
